# Download all pretrained models mentioned in srzoo-repo
wget http://mcml.yonsei.ac.kr/files/srzoo/edsr_baseline_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/edsr_baseline_x3.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/edsr_baseline_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/edsr_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/edsr_x3.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/edsr_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/eusr_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/eusr_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/eusr_x8.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/dbpn_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/dbpn_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/dbpn_x8.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/rcan_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/rcan_x3.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/rcan_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/rcan_x8.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/msrn_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/msrn_x3.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/msrn_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/4pp_eusr_pirm_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/esrgan_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/rrdb_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/carn_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/carn_x3.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/carn_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/frsr_x2.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/frsr_x3.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/frsr_x4.pb
wget http://mcml.yonsei.ac.kr/files/srzoo/natsr_x4.pb
